"""encrypt_travel_fields

Revision ID: 7924b4719685
Revises: 1350ae107d35
Create Date: 2026-01-02 11:49:31.582962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7924b4719685'
down_revision: Union[str, Sequence[str], None] = '1350ae107d35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # op.alter_column('travel_requests', 'distance_km',
    #            existing_type=sa.DOUBLE_PRECISION(precision=53),
    #            type_=models.EncryptedFloat(),
    #            existing_nullable=False)
    # op.alter_column('travel_requests', 'total_amount',
    #            existing_type=sa.DOUBLE_PRECISION(precision=53),
    #            type_=models.EncryptedFloat(),
    #            existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # op.alter_column('travel_requests', 'total_amount',
    #            existing_type=models.EncryptedFloat(),
    #            type_=sa.DOUBLE_PRECISION(precision=53),
    #            existing_nullable=False)
    # op.alter_column('travel_requests', 'distance_km',
    #            existing_type=models.EncryptedFloat(),
    #            type_=sa.DOUBLE_PRECISION(precision=53),
    #            existing_nullable=False)
    # ### end Alembic commands ###
